name: Style

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  fourmolu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: fourmolu/fourmolu-action@v11
      with:
        pattern: |
          api/**/*.hs
          server/**/*.hs
          masna3-jobs/**/*.hs
          masna3-prelude/**/*.hs

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["server/", "api/", "masna3-prelude/", "masna3-jobs/"]'
        fail-on: warning
